name: cofit
description: Engineer's degree
author: Marcin Mucha
version: 1.0.0+1

publish_to: 'none'

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.16.1
  provider: ^4.0.1
  firebase_core: ^0.5.0
  firebase_auth: ^0.18.1+1
  cloud_firestore: ^0.14.1+1
  flushbar: ^1.10.4
  cron: ^0.2.4
  shared_preferences: ^0.5.7+3
  geolocator: ^5.1.3
  flutter_local_notifications: ^4.0.0
  charts_flutter: ^0.9.0
  flutter_native_splash: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/